ALTER TABLE agents ADD COLUMN os_id TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN os_version_id TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN os_pretty_name TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN os_source TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN os_unavailable_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN os_reported_at BIGINT;
