{{- if and .Values.license.key (not .Values.license.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maintenant.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maintenant.labels" . | nindent 4 }}
type: Opaque
stringData:
  license-key: {{ .Values.license.key | quote }}
{{- end }}
