// Maintenant — Multi-Server Agent Ingest Protocol
// Feature: 012-multiserver-pro
// Status: Draft
//
// Generated stubs land in: internal/agentpb/{ingest.pb.go, ingest_grpc.pb.go}
// Build command (run when this file changes; .pb.go files are committed):
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          contracts/ingest.proto
//   mv contracts/ingest*.pb.go internal/agentpb/
//
// Wire layer is gRPC over TLS. Application-level auth is Ed25519 nonce
// signature; see AuthChallenge / AuthResponse below.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: specs/012-multiserver-pro/contracts/ingest.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ingest_RegisterAgent_FullMethodName = "/maintenant.agent.v1.Ingest/RegisterAgent"
	Ingest_Push_FullMethodName          = "/maintenant.agent.v1.Ingest/Push"
)

// IngestClient is the client API for Ingest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestClient interface {
	// RegisterAgent — first-boot enrollment.
	// Called once per agent identity. Idempotent on the server side: re-calling
	// with the same agent_id and a previously-consumed token returns
	// FailedPrecondition.
	RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Push — long-lived bidirectional stream.
	// Server first sends AuthChallenge. Client sends AuthResponse, then a
	// continuous stream of AgentEvent. Server may send error ServerMessage
	// and close the stream at any time (e.g., revocation, rate-limit).
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type ingestClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestClient(cc grpc.ClientConnInterface) IngestClient {
	return &ingestClient{cc}
}

func (c *ingestClient) RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Ingest_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ingest_ServiceDesc.Streams[0], Ingest_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingest_PushClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// IngestServer is the server API for Ingest service.
// All implementations must embed UnimplementedIngestServer
// for forward compatibility.
type IngestServer interface {
	// RegisterAgent — first-boot enrollment.
	// Called once per agent identity. Idempotent on the server side: re-calling
	// with the same agent_id and a previously-consumed token returns
	// FailedPrecondition.
	RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Push — long-lived bidirectional stream.
	// Server first sends AuthChallenge. Client sends AuthResponse, then a
	// continuous stream of AgentEvent. Server may send error ServerMessage
	// and close the stream at any time (e.g., revocation, rate-limit).
	Push(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedIngestServer()
}

// UnimplementedIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServer struct{}

func (UnimplementedIngestServer) RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedIngestServer) Push(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedIngestServer) mustEmbedUnimplementedIngestServer() {}
func (UnimplementedIngestServer) testEmbeddedByValue()                {}

// UnsafeIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServer will
// result in compilation errors.
type UnsafeIngestServer interface {
	mustEmbedUnimplementedIngestServer()
}

func RegisterIngestServer(s grpc.ServiceRegistrar, srv IngestServer) {
	// If the following call panics, it indicates UnimplementedIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ingest_ServiceDesc, srv)
}

func _Ingest_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingest_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServer).RegisterAgent(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingest_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServer).Push(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingest_PushServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// Ingest_ServiceDesc is the grpc.ServiceDesc for Ingest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maintenant.agent.v1.Ingest",
	HandlerType: (*IngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _Ingest_RegisterAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _Ingest_Push_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "specs/012-multiserver-pro/contracts/ingest.proto",
}
