// Maintenant — Multi-Server Agent Ingest Protocol
// Feature: 012-multiserver-pro
// Status: Draft
//
// Generated stubs land in: internal/agentpb/{ingest.pb.go, ingest_grpc.pb.go}
// Build command (run when this file changes; .pb.go files are committed):
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          contracts/ingest.proto
//   mv contracts/ingest*.pb.go internal/agentpb/
//
// Wire layer is gRPC over TLS. Application-level auth is Ed25519 nonce
// signature; see AuthChallenge / AuthResponse below.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: specs/012-multiserver-pro/contracts/ingest.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runtime int32

const (
	Runtime_RUNTIME_UNSPECIFIED Runtime = 0
	Runtime_RUNTIME_DOCKER      Runtime = 1
	Runtime_RUNTIME_SWARM       Runtime = 2
	Runtime_RUNTIME_KUBERNETES  Runtime = 3
)

// Enum value maps for Runtime.
var (
	Runtime_name = map[int32]string{
		0: "RUNTIME_UNSPECIFIED",
		1: "RUNTIME_DOCKER",
		2: "RUNTIME_SWARM",
		3: "RUNTIME_KUBERNETES",
	}
	Runtime_value = map[string]int32{
		"RUNTIME_UNSPECIFIED": 0,
		"RUNTIME_DOCKER":      1,
		"RUNTIME_SWARM":       2,
		"RUNTIME_KUBERNETES":  3,
	}
)

func (x Runtime) Enum() *Runtime {
	p := new(Runtime)
	*p = x
	return p
}

func (x Runtime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runtime) Descriptor() protoreflect.EnumDescriptor {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[0].Descriptor()
}

func (Runtime) Type() protoreflect.EnumType {
	return &file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[0]
}

func (x Runtime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runtime.Descriptor instead.
func (Runtime) EnumDescriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{0}
}

type ContainerState int32

const (
	ContainerState_CONTAINER_STATE_UNSPECIFIED ContainerState = 0
	ContainerState_CONTAINER_STATE_CREATED     ContainerState = 1
	ContainerState_CONTAINER_STATE_RUNNING     ContainerState = 2
	ContainerState_CONTAINER_STATE_PAUSED      ContainerState = 3
	ContainerState_CONTAINER_STATE_RESTARTING  ContainerState = 4
	ContainerState_CONTAINER_STATE_REMOVING    ContainerState = 5
	ContainerState_CONTAINER_STATE_EXITED      ContainerState = 6
	ContainerState_CONTAINER_STATE_DEAD        ContainerState = 7
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CONTAINER_STATE_UNSPECIFIED",
		1: "CONTAINER_STATE_CREATED",
		2: "CONTAINER_STATE_RUNNING",
		3: "CONTAINER_STATE_PAUSED",
		4: "CONTAINER_STATE_RESTARTING",
		5: "CONTAINER_STATE_REMOVING",
		6: "CONTAINER_STATE_EXITED",
		7: "CONTAINER_STATE_DEAD",
	}
	ContainerState_value = map[string]int32{
		"CONTAINER_STATE_UNSPECIFIED": 0,
		"CONTAINER_STATE_CREATED":     1,
		"CONTAINER_STATE_RUNNING":     2,
		"CONTAINER_STATE_PAUSED":      3,
		"CONTAINER_STATE_RESTARTING":  4,
		"CONTAINER_STATE_REMOVING":    5,
		"CONTAINER_STATE_EXITED":      6,
		"CONTAINER_STATE_DEAD":        7,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[1].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[1]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{1}
}

type EndpointStatus int32

const (
	EndpointStatus_ENDPOINT_STATUS_UNSPECIFIED EndpointStatus = 0
	EndpointStatus_ENDPOINT_STATUS_UP          EndpointStatus = 1
	EndpointStatus_ENDPOINT_STATUS_DOWN        EndpointStatus = 2
	EndpointStatus_ENDPOINT_STATUS_DEGRADED    EndpointStatus = 3
)

// Enum value maps for EndpointStatus.
var (
	EndpointStatus_name = map[int32]string{
		0: "ENDPOINT_STATUS_UNSPECIFIED",
		1: "ENDPOINT_STATUS_UP",
		2: "ENDPOINT_STATUS_DOWN",
		3: "ENDPOINT_STATUS_DEGRADED",
	}
	EndpointStatus_value = map[string]int32{
		"ENDPOINT_STATUS_UNSPECIFIED": 0,
		"ENDPOINT_STATUS_UP":          1,
		"ENDPOINT_STATUS_DOWN":        2,
		"ENDPOINT_STATUS_DEGRADED":    3,
	}
)

func (x EndpointStatus) Enum() *EndpointStatus {
	p := new(EndpointStatus)
	*p = x
	return p
}

func (x EndpointStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[2].Descriptor()
}

func (EndpointStatus) Type() protoreflect.EnumType {
	return &file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[2]
}

func (x EndpointStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointStatus.Descriptor instead.
func (EndpointStatus) EnumDescriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{2}
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // UUID v4 (lowercase, no braces) — canonical key
	PublicKey       []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                   // raw 32 bytes Ed25519
	EnrollmentToken string                 `protobuf:"bytes,3,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // "mnt_enr_..." — one-time, TTL 24h
	Hostname        string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsArch          string                 `protobuf:"bytes,5,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`                   // e.g. "linux/amd64"
	AgentVersion    string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"` // semver — server checks major compat
	DetectedRuntime Runtime                `protobuf:"varint,7,opt,name=detected_runtime,json=detectedRuntime,proto3,enum=maintenant.agent.v1.Runtime" json:"detected_runtime,omitempty"`
	// Optional display label suggested by the agent (from --label= flag or
	// the operator's preference). If empty, the server falls back to using
	// `hostname` as the initial display value. Display-only — never used as
	// an identifier in API/MCP/gRPC requests; agent_id is the only key.
	// Max 64 chars enforced server-side. Editable later via PATCH /agents/:id.
	Label         string `protobuf:"bytes,8,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetDetectedRuntime() Runtime {
	if x != nil {
		return x.DetectedRuntime
	}
	return Runtime_RUNTIME_UNSPECIFIED
}

func (x *RegisterRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // for clock-skew calibration
	AgentConfig   *AgentConfig           `protobuf:"bytes,2,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *RegisterResponse) GetAgentConfig() *AgentConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

type AgentConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side defaults pushed once at registration. The agent does NOT
	// accept dynamic reconfiguration during streaming — push-only invariant.
	ResourceSampleIntervalSeconds  uint32 `protobuf:"varint,1,opt,name=resource_sample_interval_seconds,json=resourceSampleIntervalSeconds,proto3" json:"resource_sample_interval_seconds,omitempty"`    // default 10
	CertificateScanIntervalSeconds uint32 `protobuf:"varint,2,opt,name=certificate_scan_interval_seconds,json=certificateScanIntervalSeconds,proto3" json:"certificate_scan_interval_seconds,omitempty"` // default 60
	MaxEventsPerSecond             uint32 `protobuf:"varint,3,opt,name=max_events_per_second,json=maxEventsPerSecond,proto3" json:"max_events_per_second,omitempty"`                                     // default 1000
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfig) GetResourceSampleIntervalSeconds() uint32 {
	if x != nil {
		return x.ResourceSampleIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetCertificateScanIntervalSeconds() uint32 {
	if x != nil {
		return x.CertificateScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetMaxEventsPerSecond() uint32 {
	if x != nil {
		return x.MaxEventsPerSecond
	}
	return 0
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Auth
	//	*ClientMessage_Event
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetAuth() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ClientMessage) GetEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Auth struct {
	Auth *AuthResponse `protobuf:"bytes,1,opt,name=auth,proto3,oneof"` // first message only
}

type ClientMessage_Event struct {
	Event *AgentEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"` // every subsequent message
}

func (*ClientMessage_Auth) isClientMessage_Payload() {}

func (*ClientMessage_Event) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Challenge
	//	*ServerMessage_Ack
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetChallenge() *AuthChallenge {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *ServerMessage) GetAck() *EventAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Challenge struct {
	Challenge *AuthChallenge `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"` // first message only
}

type ServerMessage_Ack struct {
	Ack *EventAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"` // optional periodic ack (every N events or T seconds)
}

type ServerMessage_Error struct {
	Error *StreamError `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // server-initiated termination signal
}

func (*ServerMessage_Challenge) isServerMessage_Payload() {}

func (*ServerMessage_Ack) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // exactly 32 bytes random, generated server-side per stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *AuthChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // UUID v4
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // unix seconds, client clock at signing time
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`            // Ed25519.Sign(privkey, signing_payload)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *AuthResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastEventSeq  uint64                 `protobuf:"varint,1,opt,name=last_event_seq,json=lastEventSeq,proto3" json:"last_event_seq,omitempty"` // monotonic counter assigned by client per-stream
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *EventAck) GetLastEventSeq() uint64 {
	if x != nil {
		return x.LastEventSeq
	}
	return 0
}

func (x *EventAck) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                        // e.g. "agent_revoked", "rate_limited", "incompatible_version"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // human-readable
	RetryAfterMs  uint32                 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // hint for client backoff (rate-limit case)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *StreamError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamError) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type AgentEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentId    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventId    string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // UUID v4 generated by agent
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Seq        uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"` // monotonic per-stream, used for EventAck
	// Types that are valid to be assigned to Body:
	//
	//	*AgentEvent_Container
	//	*AgentEvent_Endpoint
	//	*AgentEvent_Heartbeat
	//	*AgentEvent_Resource
	//	*AgentEvent_Certificate
	//	*AgentEvent_Swarm
	//	*AgentEvent_Kubernetes
	Body          isAgentEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{9}
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AgentEvent) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *AgentEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AgentEvent) GetBody() isAgentEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentEvent) GetContainer() *ContainerEvent {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Container); ok {
			return x.Container
		}
	}
	return nil
}

func (x *AgentEvent) GetEndpoint() *EndpointEvent {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Endpoint); ok {
			return x.Endpoint
		}
	}
	return nil
}

func (x *AgentEvent) GetHeartbeat() *HeartbeatEvent {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEvent) GetResource() *ResourceSample {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *AgentEvent) GetCertificate() *CertificateInfo {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Certificate); ok {
			return x.Certificate
		}
	}
	return nil
}

func (x *AgentEvent) GetSwarm() *SwarmTopology {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Swarm); ok {
			return x.Swarm
		}
	}
	return nil
}

func (x *AgentEvent) GetKubernetes() *KubernetesTopology {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Kubernetes); ok {
			return x.Kubernetes
		}
	}
	return nil
}

type isAgentEvent_Body interface {
	isAgentEvent_Body()
}

type AgentEvent_Container struct {
	Container *ContainerEvent `protobuf:"bytes,10,opt,name=container,proto3,oneof"`
}

type AgentEvent_Endpoint struct {
	Endpoint *EndpointEvent `protobuf:"bytes,11,opt,name=endpoint,proto3,oneof"`
}

type AgentEvent_Heartbeat struct {
	Heartbeat *HeartbeatEvent `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type AgentEvent_Resource struct {
	Resource *ResourceSample `protobuf:"bytes,13,opt,name=resource,proto3,oneof"`
}

type AgentEvent_Certificate struct {
	Certificate *CertificateInfo `protobuf:"bytes,14,opt,name=certificate,proto3,oneof"`
}

type AgentEvent_Swarm struct {
	Swarm *SwarmTopology `protobuf:"bytes,15,opt,name=swarm,proto3,oneof"`
}

type AgentEvent_Kubernetes struct {
	Kubernetes *KubernetesTopology `protobuf:"bytes,16,opt,name=kubernetes,proto3,oneof"`
}

func (*AgentEvent_Container) isAgentEvent_Body() {}

func (*AgentEvent_Endpoint) isAgentEvent_Body() {}

func (*AgentEvent_Heartbeat) isAgentEvent_Body() {}

func (*AgentEvent_Resource) isAgentEvent_Body() {}

func (*AgentEvent_Certificate) isAgentEvent_Body() {}

func (*AgentEvent_Swarm) isAgentEvent_Body() {}

func (*AgentEvent_Kubernetes) isAgentEvent_Body() {}

type ContainerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	State         ContainerState         `protobuf:"varint,5,opt,name=state,proto3,enum=maintenant.agent.v1.ContainerState" json:"state,omitempty"`
	StatusMessage string                 `protobuf:"bytes,6,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEvent) Reset() {
	*x = ContainerEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEvent) ProtoMessage() {}

func (x *ContainerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEvent.ProtoReflect.Descriptor instead.
func (*ContainerEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerEvent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerEvent) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ContainerEvent) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *ContainerEvent) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *ContainerEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ContainerEvent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EndpointEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"` // server-assigned, originally distributed via AgentConfig or label
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status        EndpointStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=maintenant.agent.v1.EndpointStatus" json:"status,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 0 if non-HTTP probe
	LatencyMs     uint64                 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointEvent) Reset() {
	*x = EndpointEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointEvent) ProtoMessage() {}

func (x *EndpointEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointEvent.ProtoReflect.Descriptor instead.
func (*EndpointEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{11}
}

func (x *EndpointEvent) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *EndpointEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EndpointEvent) GetStatus() EndpointStatus {
	if x != nil {
		return x.Status
	}
	return EndpointStatus_ENDPOINT_STATUS_UNSPECIFIED
}

func (x *EndpointEvent) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EndpointEvent) GetLatencyMs() uint64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *EndpointEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HeartbeatEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatToken string                 `protobuf:"bytes,1,opt,name=heartbeat_token,json=heartbeatToken,proto3" json:"heartbeat_token,omitempty"` // matches existing heartbeat token in DB
	SourceIp       string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatEvent) GetHeartbeatToken() string {
	if x != nil {
		return x.HeartbeatToken
	}
	return ""
}

func (x *HeartbeatEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

type ResourceSample struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerId      string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`                   // empty for host-level samples
	CpuPercent       float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`                    // host CPU% when container_id empty
	MemoryBytes      uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`                  // host mem used when container_id empty
	MemoryLimitBytes uint64                 `protobuf:"varint,4,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"` // host mem total when container_id empty
	NetworkRxBytes   uint64                 `protobuf:"varint,5,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes   uint64                 `protobuf:"varint,6,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	DiskReadBytes    uint64                 `protobuf:"varint,7,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes   uint64                 `protobuf:"varint,8,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"`
	// Host-level only (container_id empty): root filesystem capacity.
	HostDiskTotalBytes uint64 `protobuf:"varint,9,opt,name=host_disk_total_bytes,json=hostDiskTotalBytes,proto3" json:"host_disk_total_bytes,omitempty"`
	HostDiskUsedBytes  uint64 `protobuf:"varint,10,opt,name=host_disk_used_bytes,json=hostDiskUsedBytes,proto3" json:"host_disk_used_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceSample) Reset() {
	*x = ResourceSample{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSample) ProtoMessage() {}

func (x *ResourceSample) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSample.ProtoReflect.Descriptor instead.
func (*ResourceSample) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceSample) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ResourceSample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceSample) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceSample) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ResourceSample) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ResourceSample) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *ResourceSample) GetDiskReadBytes() uint64 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *ResourceSample) GetDiskWriteBytes() uint64 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

func (x *ResourceSample) GetHostDiskTotalBytes() uint64 {
	if x != nil {
		return x.HostDiskTotalBytes
	}
	return 0
}

func (x *ResourceSample) GetHostDiskUsedBytes() uint64 {
	if x != nil {
		return x.HostDiskUsedBytes
	}
	return 0
}

type CertificateInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Host              string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port              uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	SubjectCn         string                 `protobuf:"bytes,3,opt,name=subject_cn,json=subjectCn,proto3" json:"subject_cn,omitempty"`
	IssuerCn          string                 `protobuf:"bytes,4,opt,name=issuer_cn,json=issuerCn,proto3" json:"issuer_cn,omitempty"`
	NotBefore         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	FingerprintSha256 []byte                 `protobuf:"bytes,7,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	SanDns            []string               `protobuf:"bytes,8,rep,name=san_dns,json=sanDns,proto3" json:"san_dns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CertificateInfo) Reset() {
	*x = CertificateInfo{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateInfo) ProtoMessage() {}

func (x *CertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateInfo.ProtoReflect.Descriptor instead.
func (*CertificateInfo) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{14}
}

func (x *CertificateInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CertificateInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CertificateInfo) GetSubjectCn() string {
	if x != nil {
		return x.SubjectCn
	}
	return ""
}

func (x *CertificateInfo) GetIssuerCn() string {
	if x != nil {
		return x.IssuerCn
	}
	return ""
}

func (x *CertificateInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateInfo) GetFingerprintSha256() []byte {
	if x != nil {
		return x.FingerprintSha256
	}
	return nil
}

func (x *CertificateInfo) GetSanDns() []string {
	if x != nil {
		return x.SanDns
	}
	return nil
}

type SwarmTopology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*SwarmServiceMsg     `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Tasks         []*SwarmTaskMsg        `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Nodes         []*SwarmNodeMsg        `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmTopology) Reset() {
	*x = SwarmTopology{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmTopology) ProtoMessage() {}

func (x *SwarmTopology) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmTopology.ProtoReflect.Descriptor instead.
func (*SwarmTopology) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{15}
}

func (x *SwarmTopology) GetServices() []*SwarmServiceMsg {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *SwarmTopology) GetTasks() []*SwarmTaskMsg {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *SwarmTopology) GetNodes() []*SwarmNodeMsg {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SwarmServiceMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image           string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Mode            string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"` // "replicated" or "global"
	DesiredReplicas int32                  `protobuf:"varint,5,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	RunningReplicas int32                  `protobuf:"varint,6,opt,name=running_replicas,json=runningReplicas,proto3" json:"running_replicas,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StackName       string                 `protobuf:"bytes,8,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SwarmServiceMsg) Reset() {
	*x = SwarmServiceMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmServiceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmServiceMsg) ProtoMessage() {}

func (x *SwarmServiceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmServiceMsg.ProtoReflect.Descriptor instead.
func (*SwarmServiceMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{16}
}

func (x *SwarmServiceMsg) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SwarmServiceMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SwarmServiceMsg) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SwarmServiceMsg) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SwarmServiceMsg) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *SwarmServiceMsg) GetRunningReplicas() int32 {
	if x != nil {
		return x.RunningReplicas
	}
	return 0
}

func (x *SwarmServiceMsg) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SwarmServiceMsg) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *SwarmServiceMsg) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SwarmTaskMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Slot          int32                  `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	DesiredState  string                 `protobuf:"bytes,6,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	ContainerId   string                 `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	ExitCode      int32                  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode   bool                   `protobuf:"varint,10,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"` // proto3 has no nullable int; gate exit_code with this
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeHostname  string                 `protobuf:"bytes,12,opt,name=node_hostname,json=nodeHostname,proto3" json:"node_hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmTaskMsg) Reset() {
	*x = SwarmTaskMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmTaskMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmTaskMsg) ProtoMessage() {}

func (x *SwarmTaskMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmTaskMsg.ProtoReflect.Descriptor instead.
func (*SwarmTaskMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{17}
}

func (x *SwarmTaskMsg) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SwarmTaskMsg) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SwarmTaskMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SwarmTaskMsg) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SwarmTaskMsg) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SwarmTaskMsg) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *SwarmTaskMsg) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SwarmTaskMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SwarmTaskMsg) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SwarmTaskMsg) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *SwarmTaskMsg) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SwarmTaskMsg) GetNodeHostname() string {
	if x != nil {
		return x.NodeHostname
	}
	return ""
}

type SwarmNodeMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                 // "manager" or "worker"
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`             // "ready", "down", "disconnected", "unknown"
	Availability  string                 `protobuf:"bytes,5,opt,name=availability,proto3" json:"availability,omitempty"` // "active", "pause", "drain"
	EngineVersion string                 `protobuf:"bytes,6,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	TaskCount     int32                  `protobuf:"varint,8,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmNodeMsg) Reset() {
	*x = SwarmNodeMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmNodeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmNodeMsg) ProtoMessage() {}

func (x *SwarmNodeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmNodeMsg.ProtoReflect.Descriptor instead.
func (*SwarmNodeMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{18}
}

func (x *SwarmNodeMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SwarmNodeMsg) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SwarmNodeMsg) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SwarmNodeMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SwarmNodeMsg) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

func (x *SwarmNodeMsg) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *SwarmNodeMsg) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SwarmNodeMsg) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

type KubernetesTopology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Workloads     []*K8SWorkloadMsg      `protobuf:"bytes,2,rep,name=workloads,proto3" json:"workloads,omitempty"`
	Pods          []*K8SPodMsg           `protobuf:"bytes,3,rep,name=pods,proto3" json:"pods,omitempty"`
	Nodes         []*K8SNodeMsg          `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Events        []*K8SEventMsg         `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesTopology) Reset() {
	*x = KubernetesTopology{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesTopology) ProtoMessage() {}

func (x *KubernetesTopology) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesTopology.ProtoReflect.Descriptor instead.
func (*KubernetesTopology) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{19}
}

func (x *KubernetesTopology) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *KubernetesTopology) GetWorkloads() []*K8SWorkloadMsg {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *KubernetesTopology) GetPods() []*K8SPodMsg {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *KubernetesTopology) GetNodes() []*K8SNodeMsg {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *KubernetesTopology) GetEvents() []*K8SEventMsg {
	if x != nil {
		return x.Events
	}
	return nil
}

type K8SEventMsg struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Normal, Warning
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source            string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	FirstSeen         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Count             int32                  `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	InvolvedKind      string                 `protobuf:"bytes,8,opt,name=involved_kind,json=involvedKind,proto3" json:"involved_kind,omitempty"` // Pod, Deployment, StatefulSet, DaemonSet, Job
	InvolvedNamespace string                 `protobuf:"bytes,9,opt,name=involved_namespace,json=involvedNamespace,proto3" json:"involved_namespace,omitempty"`
	InvolvedName      string                 `protobuf:"bytes,10,opt,name=involved_name,json=involvedName,proto3" json:"involved_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *K8SEventMsg) Reset() {
	*x = K8SEventMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SEventMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SEventMsg) ProtoMessage() {}

func (x *K8SEventMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SEventMsg.ProtoReflect.Descriptor instead.
func (*K8SEventMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{20}
}

func (x *K8SEventMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *K8SEventMsg) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *K8SEventMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *K8SEventMsg) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *K8SEventMsg) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *K8SEventMsg) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *K8SEventMsg) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *K8SEventMsg) GetInvolvedKind() string {
	if x != nil {
		return x.InvolvedKind
	}
	return ""
}

func (x *K8SEventMsg) GetInvolvedNamespace() string {
	if x != nil {
		return x.InvolvedNamespace
	}
	return ""
}

func (x *K8SEventMsg) GetInvolvedName() string {
	if x != nil {
		return x.InvolvedName
	}
	return ""
}

type K8SWorkloadMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "{namespace}/{kind}/{name}"
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind            string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // Deployment, StatefulSet, DaemonSet, Job
	Images          []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	ReadyReplicas   int32                  `protobuf:"varint,6,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas int32                  `protobuf:"varint,7,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, progressing, failed
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *K8SWorkloadMsg) Reset() {
	*x = K8SWorkloadMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SWorkloadMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SWorkloadMsg) ProtoMessage() {}

func (x *K8SWorkloadMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SWorkloadMsg.ProtoReflect.Descriptor instead.
func (*K8SWorkloadMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{21}
}

func (x *K8SWorkloadMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *K8SWorkloadMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *K8SWorkloadMsg) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *K8SWorkloadMsg) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *K8SWorkloadMsg) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *K8SWorkloadMsg) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *K8SWorkloadMsg) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *K8SWorkloadMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *K8SWorkloadMsg) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type K8SPodMsg struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status        string                   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                 // Running, Pending, Succeeded, Failed, Unknown
	StatusReason  string                   `protobuf:"bytes,4,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"` // CrashLoopBackOff, ImagePullBackOff, ...
	RestartCount  int32                    `protobuf:"varint,5,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	NodeName      string                   `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodIp         string                   `protobuf:"bytes,7,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	HostIp        string                   `protobuf:"bytes,8,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	WorkloadRef   string                   `protobuf:"bytes,9,opt,name=workload_ref,json=workloadRef,proto3" json:"workload_ref,omitempty"` // owning workload ID
	Containers    []*K8SContainerStatusMsg `protobuf:"bytes,10,rep,name=containers,proto3" json:"containers,omitempty"`
	CreatedAt     *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SPodMsg) Reset() {
	*x = K8SPodMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SPodMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SPodMsg) ProtoMessage() {}

func (x *K8SPodMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SPodMsg.ProtoReflect.Descriptor instead.
func (*K8SPodMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{22}
}

func (x *K8SPodMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *K8SPodMsg) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *K8SPodMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *K8SPodMsg) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *K8SPodMsg) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *K8SPodMsg) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *K8SPodMsg) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *K8SPodMsg) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *K8SPodMsg) GetWorkloadRef() string {
	if x != nil {
		return x.WorkloadRef
	}
	return ""
}

func (x *K8SPodMsg) GetContainers() []*K8SContainerStatusMsg {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *K8SPodMsg) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type K8SContainerStatusMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	RestartCount  int32                  `protobuf:"varint,4,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // running, waiting, terminated
	StateReason   string                 `protobuf:"bytes,6,opt,name=state_reason,json=stateReason,proto3" json:"state_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SContainerStatusMsg) Reset() {
	*x = K8SContainerStatusMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SContainerStatusMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SContainerStatusMsg) ProtoMessage() {}

func (x *K8SContainerStatusMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SContainerStatusMsg.ProtoReflect.Descriptor instead.
func (*K8SContainerStatusMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{23}
}

func (x *K8SContainerStatusMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *K8SContainerStatusMsg) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *K8SContainerStatusMsg) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *K8SContainerStatusMsg) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *K8SContainerStatusMsg) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *K8SContainerStatusMsg) GetStateReason() string {
	if x != nil {
		return x.StateReason
	}
	return ""
}

type K8SNodeMsg struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Roles                    []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Status                   string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // ready, not-ready, unknown
	RunningPods              int32                  `protobuf:"varint,4,opt,name=running_pods,json=runningPods,proto3" json:"running_pods,omitempty"`
	KubernetesVersion        string                 `protobuf:"bytes,5,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	OsImage                  string                 `protobuf:"bytes,6,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	Architecture             string                 `protobuf:"bytes,7,opt,name=architecture,proto3" json:"architecture,omitempty"`
	CapacityCpuMillicores    int64                  `protobuf:"varint,8,opt,name=capacity_cpu_millicores,json=capacityCpuMillicores,proto3" json:"capacity_cpu_millicores,omitempty"`
	CapacityMemoryBytes      int64                  `protobuf:"varint,9,opt,name=capacity_memory_bytes,json=capacityMemoryBytes,proto3" json:"capacity_memory_bytes,omitempty"`
	CapacityPods             int64                  `protobuf:"varint,10,opt,name=capacity_pods,json=capacityPods,proto3" json:"capacity_pods,omitempty"`
	AllocatableCpuMillicores int64                  `protobuf:"varint,11,opt,name=allocatable_cpu_millicores,json=allocatableCpuMillicores,proto3" json:"allocatable_cpu_millicores,omitempty"`
	AllocatableMemoryBytes   int64                  `protobuf:"varint,12,opt,name=allocatable_memory_bytes,json=allocatableMemoryBytes,proto3" json:"allocatable_memory_bytes,omitempty"`
	AllocatablePods          int64                  `protobuf:"varint,13,opt,name=allocatable_pods,json=allocatablePods,proto3" json:"allocatable_pods,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *K8SNodeMsg) Reset() {
	*x = K8SNodeMsg{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodeMsg) ProtoMessage() {}

func (x *K8SNodeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodeMsg.ProtoReflect.Descriptor instead.
func (*K8SNodeMsg) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{24}
}

func (x *K8SNodeMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *K8SNodeMsg) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *K8SNodeMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *K8SNodeMsg) GetRunningPods() int32 {
	if x != nil {
		return x.RunningPods
	}
	return 0
}

func (x *K8SNodeMsg) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *K8SNodeMsg) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *K8SNodeMsg) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *K8SNodeMsg) GetCapacityCpuMillicores() int64 {
	if x != nil {
		return x.CapacityCpuMillicores
	}
	return 0
}

func (x *K8SNodeMsg) GetCapacityMemoryBytes() int64 {
	if x != nil {
		return x.CapacityMemoryBytes
	}
	return 0
}

func (x *K8SNodeMsg) GetCapacityPods() int64 {
	if x != nil {
		return x.CapacityPods
	}
	return 0
}

func (x *K8SNodeMsg) GetAllocatableCpuMillicores() int64 {
	if x != nil {
		return x.AllocatableCpuMillicores
	}
	return 0
}

func (x *K8SNodeMsg) GetAllocatableMemoryBytes() int64 {
	if x != nil {
		return x.AllocatableMemoryBytes
	}
	return 0
}

func (x *K8SNodeMsg) GetAllocatablePods() int64 {
	if x != nil {
		return x.AllocatablePods
	}
	return 0
}

func (x *K8SNodeMsg) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_specs_012_multiserver_pro_contracts_ingest_proto protoreflect.FileDescriptor

const file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc = "" +
	"\n" +
	"0specs/012-multiserver-pro/contracts/ingest.proto\x12\x13maintenant.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12)\n" +
	"\x10enrollment_token\x18\x03 \x01(\tR\x0fenrollmentToken\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_arch\x18\x05 \x01(\tR\x06osArch\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12G\n" +
	"\x10detected_runtime\x18\a \x01(\x0e2\x1c.maintenant.agent.v1.RuntimeR\x0fdetectedRuntime\x12\x14\n" +
	"\x05label\x18\b \x01(\tR\x05label\"\x94\x01\n" +
	"\x10RegisterResponse\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12C\n" +
	"\fagent_config\x18\x02 \x01(\v2 .maintenant.agent.v1.AgentConfigR\vagentConfig\"\xd4\x01\n" +
	"\vAgentConfig\x12G\n" +
	" resource_sample_interval_seconds\x18\x01 \x01(\rR\x1dresourceSampleIntervalSeconds\x12I\n" +
	"!certificate_scan_interval_seconds\x18\x02 \x01(\rR\x1ecertificateScanIntervalSeconds\x121\n" +
	"\x15max_events_per_second\x18\x03 \x01(\rR\x12maxEventsPerSecond\"\x8c\x01\n" +
	"\rClientMessage\x127\n" +
	"\x04auth\x18\x01 \x01(\v2!.maintenant.agent.v1.AuthResponseH\x00R\x04auth\x127\n" +
	"\x05event\x18\x02 \x01(\v2\x1f.maintenant.agent.v1.AgentEventH\x00R\x05eventB\t\n" +
	"\apayload\"\xcb\x01\n" +
	"\rServerMessage\x12B\n" +
	"\tchallenge\x18\x01 \x01(\v2\".maintenant.agent.v1.AuthChallengeH\x00R\tchallenge\x121\n" +
	"\x03ack\x18\x02 \x01(\v2\x1d.maintenant.agent.v1.EventAckH\x00R\x03ack\x128\n" +
	"\x05error\x18\x03 \x01(\v2 .maintenant.agent.v1.StreamErrorH\x00R\x05errorB\t\n" +
	"\apayload\"%\n" +
	"\rAuthChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"e\n" +
	"\fAuthResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"m\n" +
	"\bEventAck\x12$\n" +
	"\x0elast_event_seq\x18\x01 \x01(\x04R\flastEventSeq\x12;\n" +
	"\vreceived_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"a\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\"\xf9\x04\n" +
	"\n" +
	"AgentEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12C\n" +
	"\tcontainer\x18\n" +
	" \x01(\v2#.maintenant.agent.v1.ContainerEventH\x00R\tcontainer\x12@\n" +
	"\bendpoint\x18\v \x01(\v2\".maintenant.agent.v1.EndpointEventH\x00R\bendpoint\x12C\n" +
	"\theartbeat\x18\f \x01(\v2#.maintenant.agent.v1.HeartbeatEventH\x00R\theartbeat\x12A\n" +
	"\bresource\x18\r \x01(\v2#.maintenant.agent.v1.ResourceSampleH\x00R\bresource\x12H\n" +
	"\vcertificate\x18\x0e \x01(\v2$.maintenant.agent.v1.CertificateInfoH\x00R\vcertificate\x12:\n" +
	"\x05swarm\x18\x0f \x01(\v2\".maintenant.agent.v1.SwarmTopologyH\x00R\x05swarm\x12I\n" +
	"\n" +
	"kubernetes\x18\x10 \x01(\v2'.maintenant.agent.v1.KubernetesTopologyH\x00R\n" +
	"kubernetesB\x06\n" +
	"\x04body\"\xa1\x03\n" +
	"\x0eContainerEvent\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x129\n" +
	"\x05state\x18\x05 \x01(\x0e2#.maintenant.agent.v1.ContainerStateR\x05state\x12%\n" +
	"\x0estatus_message\x18\x06 \x01(\tR\rstatusMessage\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12G\n" +
	"\x06labels\x18\b \x03(\v2/.maintenant.agent.v1.ContainerEvent.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\rEndpointEvent\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.maintenant.agent.v1.EndpointStatusR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x04R\tlatencyMs\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"V\n" +
	"\x0eHeartbeatEvent\x12'\n" +
	"\x0fheartbeat_token\x18\x01 \x01(\tR\x0eheartbeatToken\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\"\xaf\x03\n" +
	"\x0eResourceSample\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x04 \x01(\x04R\x10memoryLimitBytes\x12(\n" +
	"\x10network_rx_bytes\x18\x05 \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x06 \x01(\x04R\x0enetworkTxBytes\x12&\n" +
	"\x0fdisk_read_bytes\x18\a \x01(\x04R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\b \x01(\x04R\x0ediskWriteBytes\x121\n" +
	"\x15host_disk_total_bytes\x18\t \x01(\x04R\x12hostDiskTotalBytes\x12/\n" +
	"\x14host_disk_used_bytes\x18\n" +
	" \x01(\x04R\x11hostDiskUsedBytes\"\xb1\x02\n" +
	"\x0fCertificateInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"subject_cn\x18\x03 \x01(\tR\tsubjectCn\x12\x1b\n" +
	"\tissuer_cn\x18\x04 \x01(\tR\bissuerCn\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12-\n" +
	"\x12fingerprint_sha256\x18\a \x01(\fR\x11fingerprintSha256\x12\x17\n" +
	"\asan_dns\x18\b \x03(\tR\x06sanDns\"\xc3\x01\n" +
	"\rSwarmTopology\x12@\n" +
	"\bservices\x18\x01 \x03(\v2$.maintenant.agent.v1.SwarmServiceMsgR\bservices\x127\n" +
	"\x05tasks\x18\x02 \x03(\v2!.maintenant.agent.v1.SwarmTaskMsgR\x05tasks\x127\n" +
	"\x05nodes\x18\x03 \x03(\v2!.maintenant.agent.v1.SwarmNodeMsgR\x05nodes\"\xa3\x03\n" +
	"\x0fSwarmServiceMsg\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12)\n" +
	"\x10desired_replicas\x18\x05 \x01(\x05R\x0fdesiredReplicas\x12)\n" +
	"\x10running_replicas\x18\x06 \x01(\x05R\x0frunningReplicas\x12H\n" +
	"\x06labels\x18\a \x03(\v20.maintenant.agent.v1.SwarmServiceMsg.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"stack_name\x18\b \x01(\tR\tstackName\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x03\n" +
	"\fSwarmTaskMsg\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\x05R\x04slot\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12#\n" +
	"\rdesired_state\x18\x06 \x01(\tR\fdesiredState\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\n" +
	" \x01(\bR\vhasExitCode\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rnode_hostname\x18\f \x01(\tR\fnodeHostname\"\xf3\x01\n" +
	"\fSwarmNodeMsg\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\"\n" +
	"\favailability\x18\x05 \x01(\tR\favailability\x12%\n" +
	"\x0eengine_version\x18\x06 \x01(\tR\rengineVersion\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"task_count\x18\b \x01(\x05R\ttaskCount\"\x9c\x02\n" +
	"\x12KubernetesTopology\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12A\n" +
	"\tworkloads\x18\x02 \x03(\v2#.maintenant.agent.v1.K8sWorkloadMsgR\tworkloads\x122\n" +
	"\x04pods\x18\x03 \x03(\v2\x1e.maintenant.agent.v1.K8sPodMsgR\x04pods\x125\n" +
	"\x05nodes\x18\x04 \x03(\v2\x1f.maintenant.agent.v1.K8sNodeMsgR\x05nodes\x128\n" +
	"\x06events\x18\x05 \x03(\v2 .maintenant.agent.v1.K8sEventMsgR\x06events\"\xee\x02\n" +
	"\vK8sEventMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\n" +
	"first_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x14\n" +
	"\x05count\x18\a \x01(\x05R\x05count\x12#\n" +
	"\rinvolved_kind\x18\b \x01(\tR\finvolvedKind\x12-\n" +
	"\x12involved_namespace\x18\t \x01(\tR\x11involvedNamespace\x12#\n" +
	"\rinvolved_name\x18\n" +
	" \x01(\tR\finvolvedName\"\xa3\x02\n" +
	"\x0eK8sWorkloadMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12%\n" +
	"\x0eready_replicas\x18\x06 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10desired_replicas\x18\a \x01(\x05R\x0fdesiredReplicas\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x96\x03\n" +
	"\tK8sPodMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rstatus_reason\x18\x04 \x01(\tR\fstatusReason\x12#\n" +
	"\rrestart_count\x18\x05 \x01(\x05R\frestartCount\x12\x1b\n" +
	"\tnode_name\x18\x06 \x01(\tR\bnodeName\x12\x15\n" +
	"\x06pod_ip\x18\a \x01(\tR\x05podIp\x12\x17\n" +
	"\ahost_ip\x18\b \x01(\tR\x06hostIp\x12!\n" +
	"\fworkload_ref\x18\t \x01(\tR\vworkloadRef\x12J\n" +
	"\n" +
	"containers\x18\n" +
	" \x03(\v2*.maintenant.agent.v1.K8sContainerStatusMsgR\n" +
	"containers\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb5\x01\n" +
	"\x15K8sContainerStatusMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12#\n" +
	"\rrestart_count\x18\x04 \x01(\x05R\frestartCount\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12!\n" +
	"\fstate_reason\x18\x06 \x01(\tR\vstateReason\"\xce\x04\n" +
	"\n" +
	"K8sNodeMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\frunning_pods\x18\x04 \x01(\x05R\vrunningPods\x12-\n" +
	"\x12kubernetes_version\x18\x05 \x01(\tR\x11kubernetesVersion\x12\x19\n" +
	"\bos_image\x18\x06 \x01(\tR\aosImage\x12\"\n" +
	"\farchitecture\x18\a \x01(\tR\farchitecture\x126\n" +
	"\x17capacity_cpu_millicores\x18\b \x01(\x03R\x15capacityCpuMillicores\x122\n" +
	"\x15capacity_memory_bytes\x18\t \x01(\x03R\x13capacityMemoryBytes\x12#\n" +
	"\rcapacity_pods\x18\n" +
	" \x01(\x03R\fcapacityPods\x12<\n" +
	"\x1aallocatable_cpu_millicores\x18\v \x01(\x03R\x18allocatableCpuMillicores\x128\n" +
	"\x18allocatable_memory_bytes\x18\f \x01(\x03R\x16allocatableMemoryBytes\x12)\n" +
	"\x10allocatable_pods\x18\r \x01(\x03R\x0fallocatablePods\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*a\n" +
	"\aRuntime\x12\x17\n" +
	"\x13RUNTIME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRUNTIME_DOCKER\x10\x01\x12\x11\n" +
	"\rRUNTIME_SWARM\x10\x02\x12\x16\n" +
	"\x12RUNTIME_KUBERNETES\x10\x03*\xfb\x01\n" +
	"\x0eContainerState\x12\x1f\n" +
	"\x1bCONTAINER_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTAINER_STATE_CREATED\x10\x01\x12\x1b\n" +
	"\x17CONTAINER_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16CONTAINER_STATE_PAUSED\x10\x03\x12\x1e\n" +
	"\x1aCONTAINER_STATE_RESTARTING\x10\x04\x12\x1c\n" +
	"\x18CONTAINER_STATE_REMOVING\x10\x05\x12\x1a\n" +
	"\x16CONTAINER_STATE_EXITED\x10\x06\x12\x18\n" +
	"\x14CONTAINER_STATE_DEAD\x10\a*\x81\x01\n" +
	"\x0eEndpointStatus\x12\x1f\n" +
	"\x1bENDPOINT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENDPOINT_STATUS_UP\x10\x01\x12\x18\n" +
	"\x14ENDPOINT_STATUS_DOWN\x10\x02\x12\x1c\n" +
	"\x18ENDPOINT_STATUS_DEGRADED\x10\x032\xba\x01\n" +
	"\x06Ingest\x12\\\n" +
	"\rRegisterAgent\x12$.maintenant.agent.v1.RegisterRequest\x1a%.maintenant.agent.v1.RegisterResponse\x12R\n" +
	"\x04Push\x12\".maintenant.agent.v1.ClientMessage\x1a\".maintenant.agent.v1.ServerMessage(\x010\x01B9Z7github.com/kolapsis/maintenant/internal/agentpb;agentpbb\x06proto3"

var (
	file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescOnce sync.Once
	file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescData []byte
)

func file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP() []byte {
	file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescOnce.Do(func() {
		file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc), len(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc)))
	})
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescData
}

var file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_specs_012_multiserver_pro_contracts_ingest_proto_goTypes = []any{
	(Runtime)(0),                  // 0: maintenant.agent.v1.Runtime
	(ContainerState)(0),           // 1: maintenant.agent.v1.ContainerState
	(EndpointStatus)(0),           // 2: maintenant.agent.v1.EndpointStatus
	(*RegisterRequest)(nil),       // 3: maintenant.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 4: maintenant.agent.v1.RegisterResponse
	(*AgentConfig)(nil),           // 5: maintenant.agent.v1.AgentConfig
	(*ClientMessage)(nil),         // 6: maintenant.agent.v1.ClientMessage
	(*ServerMessage)(nil),         // 7: maintenant.agent.v1.ServerMessage
	(*AuthChallenge)(nil),         // 8: maintenant.agent.v1.AuthChallenge
	(*AuthResponse)(nil),          // 9: maintenant.agent.v1.AuthResponse
	(*EventAck)(nil),              // 10: maintenant.agent.v1.EventAck
	(*StreamError)(nil),           // 11: maintenant.agent.v1.StreamError
	(*AgentEvent)(nil),            // 12: maintenant.agent.v1.AgentEvent
	(*ContainerEvent)(nil),        // 13: maintenant.agent.v1.ContainerEvent
	(*EndpointEvent)(nil),         // 14: maintenant.agent.v1.EndpointEvent
	(*HeartbeatEvent)(nil),        // 15: maintenant.agent.v1.HeartbeatEvent
	(*ResourceSample)(nil),        // 16: maintenant.agent.v1.ResourceSample
	(*CertificateInfo)(nil),       // 17: maintenant.agent.v1.CertificateInfo
	(*SwarmTopology)(nil),         // 18: maintenant.agent.v1.SwarmTopology
	(*SwarmServiceMsg)(nil),       // 19: maintenant.agent.v1.SwarmServiceMsg
	(*SwarmTaskMsg)(nil),          // 20: maintenant.agent.v1.SwarmTaskMsg
	(*SwarmNodeMsg)(nil),          // 21: maintenant.agent.v1.SwarmNodeMsg
	(*KubernetesTopology)(nil),    // 22: maintenant.agent.v1.KubernetesTopology
	(*K8SEventMsg)(nil),           // 23: maintenant.agent.v1.K8sEventMsg
	(*K8SWorkloadMsg)(nil),        // 24: maintenant.agent.v1.K8sWorkloadMsg
	(*K8SPodMsg)(nil),             // 25: maintenant.agent.v1.K8sPodMsg
	(*K8SContainerStatusMsg)(nil), // 26: maintenant.agent.v1.K8sContainerStatusMsg
	(*K8SNodeMsg)(nil),            // 27: maintenant.agent.v1.K8sNodeMsg
	nil,                           // 28: maintenant.agent.v1.ContainerEvent.LabelsEntry
	nil,                           // 29: maintenant.agent.v1.SwarmServiceMsg.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_specs_012_multiserver_pro_contracts_ingest_proto_depIdxs = []int32{
	0,  // 0: maintenant.agent.v1.RegisterRequest.detected_runtime:type_name -> maintenant.agent.v1.Runtime
	30, // 1: maintenant.agent.v1.RegisterResponse.server_time:type_name -> google.protobuf.Timestamp
	5,  // 2: maintenant.agent.v1.RegisterResponse.agent_config:type_name -> maintenant.agent.v1.AgentConfig
	9,  // 3: maintenant.agent.v1.ClientMessage.auth:type_name -> maintenant.agent.v1.AuthResponse
	12, // 4: maintenant.agent.v1.ClientMessage.event:type_name -> maintenant.agent.v1.AgentEvent
	8,  // 5: maintenant.agent.v1.ServerMessage.challenge:type_name -> maintenant.agent.v1.AuthChallenge
	10, // 6: maintenant.agent.v1.ServerMessage.ack:type_name -> maintenant.agent.v1.EventAck
	11, // 7: maintenant.agent.v1.ServerMessage.error:type_name -> maintenant.agent.v1.StreamError
	30, // 8: maintenant.agent.v1.EventAck.received_at:type_name -> google.protobuf.Timestamp
	30, // 9: maintenant.agent.v1.AgentEvent.observed_at:type_name -> google.protobuf.Timestamp
	13, // 10: maintenant.agent.v1.AgentEvent.container:type_name -> maintenant.agent.v1.ContainerEvent
	14, // 11: maintenant.agent.v1.AgentEvent.endpoint:type_name -> maintenant.agent.v1.EndpointEvent
	15, // 12: maintenant.agent.v1.AgentEvent.heartbeat:type_name -> maintenant.agent.v1.HeartbeatEvent
	16, // 13: maintenant.agent.v1.AgentEvent.resource:type_name -> maintenant.agent.v1.ResourceSample
	17, // 14: maintenant.agent.v1.AgentEvent.certificate:type_name -> maintenant.agent.v1.CertificateInfo
	18, // 15: maintenant.agent.v1.AgentEvent.swarm:type_name -> maintenant.agent.v1.SwarmTopology
	22, // 16: maintenant.agent.v1.AgentEvent.kubernetes:type_name -> maintenant.agent.v1.KubernetesTopology
	1,  // 17: maintenant.agent.v1.ContainerEvent.state:type_name -> maintenant.agent.v1.ContainerState
	30, // 18: maintenant.agent.v1.ContainerEvent.started_at:type_name -> google.protobuf.Timestamp
	28, // 19: maintenant.agent.v1.ContainerEvent.labels:type_name -> maintenant.agent.v1.ContainerEvent.LabelsEntry
	2,  // 20: maintenant.agent.v1.EndpointEvent.status:type_name -> maintenant.agent.v1.EndpointStatus
	30, // 21: maintenant.agent.v1.CertificateInfo.not_before:type_name -> google.protobuf.Timestamp
	30, // 22: maintenant.agent.v1.CertificateInfo.not_after:type_name -> google.protobuf.Timestamp
	19, // 23: maintenant.agent.v1.SwarmTopology.services:type_name -> maintenant.agent.v1.SwarmServiceMsg
	20, // 24: maintenant.agent.v1.SwarmTopology.tasks:type_name -> maintenant.agent.v1.SwarmTaskMsg
	21, // 25: maintenant.agent.v1.SwarmTopology.nodes:type_name -> maintenant.agent.v1.SwarmNodeMsg
	29, // 26: maintenant.agent.v1.SwarmServiceMsg.labels:type_name -> maintenant.agent.v1.SwarmServiceMsg.LabelsEntry
	30, // 27: maintenant.agent.v1.SwarmServiceMsg.created_at:type_name -> google.protobuf.Timestamp
	30, // 28: maintenant.agent.v1.SwarmTaskMsg.timestamp:type_name -> google.protobuf.Timestamp
	24, // 29: maintenant.agent.v1.KubernetesTopology.workloads:type_name -> maintenant.agent.v1.K8sWorkloadMsg
	25, // 30: maintenant.agent.v1.KubernetesTopology.pods:type_name -> maintenant.agent.v1.K8sPodMsg
	27, // 31: maintenant.agent.v1.KubernetesTopology.nodes:type_name -> maintenant.agent.v1.K8sNodeMsg
	23, // 32: maintenant.agent.v1.KubernetesTopology.events:type_name -> maintenant.agent.v1.K8sEventMsg
	30, // 33: maintenant.agent.v1.K8sEventMsg.first_seen:type_name -> google.protobuf.Timestamp
	30, // 34: maintenant.agent.v1.K8sEventMsg.last_seen:type_name -> google.protobuf.Timestamp
	30, // 35: maintenant.agent.v1.K8sWorkloadMsg.created_at:type_name -> google.protobuf.Timestamp
	26, // 36: maintenant.agent.v1.K8sPodMsg.containers:type_name -> maintenant.agent.v1.K8sContainerStatusMsg
	30, // 37: maintenant.agent.v1.K8sPodMsg.created_at:type_name -> google.protobuf.Timestamp
	30, // 38: maintenant.agent.v1.K8sNodeMsg.created_at:type_name -> google.protobuf.Timestamp
	3,  // 39: maintenant.agent.v1.Ingest.RegisterAgent:input_type -> maintenant.agent.v1.RegisterRequest
	6,  // 40: maintenant.agent.v1.Ingest.Push:input_type -> maintenant.agent.v1.ClientMessage
	4,  // 41: maintenant.agent.v1.Ingest.RegisterAgent:output_type -> maintenant.agent.v1.RegisterResponse
	7,  // 42: maintenant.agent.v1.Ingest.Push:output_type -> maintenant.agent.v1.ServerMessage
	41, // [41:43] is the sub-list for method output_type
	39, // [39:41] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_specs_012_multiserver_pro_contracts_ingest_proto_init() }
func file_specs_012_multiserver_pro_contracts_ingest_proto_init() {
	if File_specs_012_multiserver_pro_contracts_ingest_proto != nil {
		return
	}
	file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientMessage_Auth)(nil),
		(*ClientMessage_Event)(nil),
	}
	file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_Challenge)(nil),
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_Error)(nil),
	}
	file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[9].OneofWrappers = []any{
		(*AgentEvent_Container)(nil),
		(*AgentEvent_Endpoint)(nil),
		(*AgentEvent_Heartbeat)(nil),
		(*AgentEvent_Resource)(nil),
		(*AgentEvent_Certificate)(nil),
		(*AgentEvent_Swarm)(nil),
		(*AgentEvent_Kubernetes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc), len(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_specs_012_multiserver_pro_contracts_ingest_proto_goTypes,
		DependencyIndexes: file_specs_012_multiserver_pro_contracts_ingest_proto_depIdxs,
		EnumInfos:         file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes,
		MessageInfos:      file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes,
	}.Build()
	File_specs_012_multiserver_pro_contracts_ingest_proto = out.File
	file_specs_012_multiserver_pro_contracts_ingest_proto_goTypes = nil
	file_specs_012_multiserver_pro_contracts_ingest_proto_depIdxs = nil
}
