// Maintenant — Multi-Server Agent Ingest Protocol
// Feature: 012-multiserver-pro
// Status: Draft
//
// Generated stubs land in: internal/agentpb/{ingest.pb.go, ingest_grpc.pb.go}
// Build command (run when this file changes; .pb.go files are committed):
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          contracts/ingest.proto
//   mv contracts/ingest*.pb.go internal/agentpb/
//
// Wire layer is gRPC over TLS. Application-level auth is Ed25519 nonce
// signature; see AuthChallenge / AuthResponse below.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: specs/012-multiserver-pro/contracts/ingest.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runtime int32

const (
	Runtime_RUNTIME_UNSPECIFIED Runtime = 0
	Runtime_RUNTIME_DOCKER      Runtime = 1
	Runtime_RUNTIME_SWARM       Runtime = 2
	Runtime_RUNTIME_KUBERNETES  Runtime = 3
)

// Enum value maps for Runtime.
var (
	Runtime_name = map[int32]string{
		0: "RUNTIME_UNSPECIFIED",
		1: "RUNTIME_DOCKER",
		2: "RUNTIME_SWARM",
		3: "RUNTIME_KUBERNETES",
	}
	Runtime_value = map[string]int32{
		"RUNTIME_UNSPECIFIED": 0,
		"RUNTIME_DOCKER":      1,
		"RUNTIME_SWARM":       2,
		"RUNTIME_KUBERNETES":  3,
	}
)

func (x Runtime) Enum() *Runtime {
	p := new(Runtime)
	*p = x
	return p
}

func (x Runtime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runtime) Descriptor() protoreflect.EnumDescriptor {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[0].Descriptor()
}

func (Runtime) Type() protoreflect.EnumType {
	return &file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[0]
}

func (x Runtime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runtime.Descriptor instead.
func (Runtime) EnumDescriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{0}
}

type ContainerState int32

const (
	ContainerState_CONTAINER_STATE_UNSPECIFIED ContainerState = 0
	ContainerState_CONTAINER_STATE_CREATED     ContainerState = 1
	ContainerState_CONTAINER_STATE_RUNNING     ContainerState = 2
	ContainerState_CONTAINER_STATE_PAUSED      ContainerState = 3
	ContainerState_CONTAINER_STATE_RESTARTING  ContainerState = 4
	ContainerState_CONTAINER_STATE_REMOVING    ContainerState = 5
	ContainerState_CONTAINER_STATE_EXITED      ContainerState = 6
	ContainerState_CONTAINER_STATE_DEAD        ContainerState = 7
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CONTAINER_STATE_UNSPECIFIED",
		1: "CONTAINER_STATE_CREATED",
		2: "CONTAINER_STATE_RUNNING",
		3: "CONTAINER_STATE_PAUSED",
		4: "CONTAINER_STATE_RESTARTING",
		5: "CONTAINER_STATE_REMOVING",
		6: "CONTAINER_STATE_EXITED",
		7: "CONTAINER_STATE_DEAD",
	}
	ContainerState_value = map[string]int32{
		"CONTAINER_STATE_UNSPECIFIED": 0,
		"CONTAINER_STATE_CREATED":     1,
		"CONTAINER_STATE_RUNNING":     2,
		"CONTAINER_STATE_PAUSED":      3,
		"CONTAINER_STATE_RESTARTING":  4,
		"CONTAINER_STATE_REMOVING":    5,
		"CONTAINER_STATE_EXITED":      6,
		"CONTAINER_STATE_DEAD":        7,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[1].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[1]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{1}
}

type EndpointStatus int32

const (
	EndpointStatus_ENDPOINT_STATUS_UNSPECIFIED EndpointStatus = 0
	EndpointStatus_ENDPOINT_STATUS_UP          EndpointStatus = 1
	EndpointStatus_ENDPOINT_STATUS_DOWN        EndpointStatus = 2
	EndpointStatus_ENDPOINT_STATUS_DEGRADED    EndpointStatus = 3
)

// Enum value maps for EndpointStatus.
var (
	EndpointStatus_name = map[int32]string{
		0: "ENDPOINT_STATUS_UNSPECIFIED",
		1: "ENDPOINT_STATUS_UP",
		2: "ENDPOINT_STATUS_DOWN",
		3: "ENDPOINT_STATUS_DEGRADED",
	}
	EndpointStatus_value = map[string]int32{
		"ENDPOINT_STATUS_UNSPECIFIED": 0,
		"ENDPOINT_STATUS_UP":          1,
		"ENDPOINT_STATUS_DOWN":        2,
		"ENDPOINT_STATUS_DEGRADED":    3,
	}
)

func (x EndpointStatus) Enum() *EndpointStatus {
	p := new(EndpointStatus)
	*p = x
	return p
}

func (x EndpointStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[2].Descriptor()
}

func (EndpointStatus) Type() protoreflect.EnumType {
	return &file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes[2]
}

func (x EndpointStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointStatus.Descriptor instead.
func (EndpointStatus) EnumDescriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{2}
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // UUID v4 (lowercase, no braces) — canonical key
	PublicKey       []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                   // raw 32 bytes Ed25519
	EnrollmentToken string                 `protobuf:"bytes,3,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // "mnt_enr_..." — one-time, TTL 24h
	Hostname        string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsArch          string                 `protobuf:"bytes,5,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`                   // e.g. "linux/amd64"
	AgentVersion    string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"` // semver — server checks major compat
	DetectedRuntime Runtime                `protobuf:"varint,7,opt,name=detected_runtime,json=detectedRuntime,proto3,enum=maintenant.agent.v1.Runtime" json:"detected_runtime,omitempty"`
	// Optional display label suggested by the agent (from --label= flag or
	// the operator's preference). If empty, the server falls back to using
	// `hostname` as the initial display value. Display-only — never used as
	// an identifier in API/MCP/gRPC requests; agent_id is the only key.
	// Max 64 chars enforced server-side. Editable later via PATCH /agents/:id.
	Label         string `protobuf:"bytes,8,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetDetectedRuntime() Runtime {
	if x != nil {
		return x.DetectedRuntime
	}
	return Runtime_RUNTIME_UNSPECIFIED
}

func (x *RegisterRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // for clock-skew calibration
	AgentConfig   *AgentConfig           `protobuf:"bytes,2,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *RegisterResponse) GetAgentConfig() *AgentConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

type AgentConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side defaults pushed once at registration. The agent does NOT
	// accept dynamic reconfiguration during streaming — push-only invariant.
	ResourceSampleIntervalSeconds  uint32 `protobuf:"varint,1,opt,name=resource_sample_interval_seconds,json=resourceSampleIntervalSeconds,proto3" json:"resource_sample_interval_seconds,omitempty"`    // default 10
	CertificateScanIntervalSeconds uint32 `protobuf:"varint,2,opt,name=certificate_scan_interval_seconds,json=certificateScanIntervalSeconds,proto3" json:"certificate_scan_interval_seconds,omitempty"` // default 60
	MaxEventsPerSecond             uint32 `protobuf:"varint,3,opt,name=max_events_per_second,json=maxEventsPerSecond,proto3" json:"max_events_per_second,omitempty"`                                     // default 1000
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfig) GetResourceSampleIntervalSeconds() uint32 {
	if x != nil {
		return x.ResourceSampleIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetCertificateScanIntervalSeconds() uint32 {
	if x != nil {
		return x.CertificateScanIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetMaxEventsPerSecond() uint32 {
	if x != nil {
		return x.MaxEventsPerSecond
	}
	return 0
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Auth
	//	*ClientMessage_Event
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetAuth() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ClientMessage) GetEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Auth struct {
	Auth *AuthResponse `protobuf:"bytes,1,opt,name=auth,proto3,oneof"` // first message only
}

type ClientMessage_Event struct {
	Event *AgentEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"` // every subsequent message
}

func (*ClientMessage_Auth) isClientMessage_Payload() {}

func (*ClientMessage_Event) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Challenge
	//	*ServerMessage_Ack
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetChallenge() *AuthChallenge {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *ServerMessage) GetAck() *EventAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Challenge struct {
	Challenge *AuthChallenge `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"` // first message only
}

type ServerMessage_Ack struct {
	Ack *EventAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"` // optional periodic ack (every N events or T seconds)
}

type ServerMessage_Error struct {
	Error *StreamError `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // server-initiated termination signal
}

func (*ServerMessage_Challenge) isServerMessage_Payload() {}

func (*ServerMessage_Ack) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // exactly 32 bytes random, generated server-side per stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *AuthChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // UUID v4
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // unix seconds, client clock at signing time
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`            // Ed25519.Sign(privkey, signing_payload)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *AuthResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastEventSeq  uint64                 `protobuf:"varint,1,opt,name=last_event_seq,json=lastEventSeq,proto3" json:"last_event_seq,omitempty"` // monotonic counter assigned by client per-stream
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *EventAck) GetLastEventSeq() uint64 {
	if x != nil {
		return x.LastEventSeq
	}
	return 0
}

func (x *EventAck) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                        // e.g. "agent_revoked", "rate_limited", "incompatible_version"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // human-readable
	RetryAfterMs  uint32                 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // hint for client backoff (rate-limit case)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *StreamError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamError) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type AgentEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentId    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventId    string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // UUID v4 generated by agent
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Seq        uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"` // monotonic per-stream, used for EventAck
	// Types that are valid to be assigned to Body:
	//
	//	*AgentEvent_Container
	//	*AgentEvent_Endpoint
	//	*AgentEvent_Heartbeat
	//	*AgentEvent_Resource
	//	*AgentEvent_Certificate
	Body          isAgentEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{9}
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AgentEvent) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *AgentEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AgentEvent) GetBody() isAgentEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentEvent) GetContainer() *ContainerEvent {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Container); ok {
			return x.Container
		}
	}
	return nil
}

func (x *AgentEvent) GetEndpoint() *EndpointEvent {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Endpoint); ok {
			return x.Endpoint
		}
	}
	return nil
}

func (x *AgentEvent) GetHeartbeat() *HeartbeatEvent {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEvent) GetResource() *ResourceSample {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *AgentEvent) GetCertificate() *CertificateInfo {
	if x != nil {
		if x, ok := x.Body.(*AgentEvent_Certificate); ok {
			return x.Certificate
		}
	}
	return nil
}

type isAgentEvent_Body interface {
	isAgentEvent_Body()
}

type AgentEvent_Container struct {
	Container *ContainerEvent `protobuf:"bytes,10,opt,name=container,proto3,oneof"`
}

type AgentEvent_Endpoint struct {
	Endpoint *EndpointEvent `protobuf:"bytes,11,opt,name=endpoint,proto3,oneof"`
}

type AgentEvent_Heartbeat struct {
	Heartbeat *HeartbeatEvent `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type AgentEvent_Resource struct {
	Resource *ResourceSample `protobuf:"bytes,13,opt,name=resource,proto3,oneof"`
}

type AgentEvent_Certificate struct {
	Certificate *CertificateInfo `protobuf:"bytes,14,opt,name=certificate,proto3,oneof"`
}

func (*AgentEvent_Container) isAgentEvent_Body() {}

func (*AgentEvent_Endpoint) isAgentEvent_Body() {}

func (*AgentEvent_Heartbeat) isAgentEvent_Body() {}

func (*AgentEvent_Resource) isAgentEvent_Body() {}

func (*AgentEvent_Certificate) isAgentEvent_Body() {}

type ContainerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	State         ContainerState         `protobuf:"varint,5,opt,name=state,proto3,enum=maintenant.agent.v1.ContainerState" json:"state,omitempty"`
	StatusMessage string                 `protobuf:"bytes,6,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEvent) Reset() {
	*x = ContainerEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEvent) ProtoMessage() {}

func (x *ContainerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEvent.ProtoReflect.Descriptor instead.
func (*ContainerEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerEvent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerEvent) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ContainerEvent) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *ContainerEvent) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *ContainerEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ContainerEvent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EndpointEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"` // server-assigned, originally distributed via AgentConfig or label
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status        EndpointStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=maintenant.agent.v1.EndpointStatus" json:"status,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 0 if non-HTTP probe
	LatencyMs     uint64                 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointEvent) Reset() {
	*x = EndpointEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointEvent) ProtoMessage() {}

func (x *EndpointEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointEvent.ProtoReflect.Descriptor instead.
func (*EndpointEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{11}
}

func (x *EndpointEvent) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *EndpointEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EndpointEvent) GetStatus() EndpointStatus {
	if x != nil {
		return x.Status
	}
	return EndpointStatus_ENDPOINT_STATUS_UNSPECIFIED
}

func (x *EndpointEvent) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EndpointEvent) GetLatencyMs() uint64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *EndpointEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HeartbeatEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatToken string                 `protobuf:"bytes,1,opt,name=heartbeat_token,json=heartbeatToken,proto3" json:"heartbeat_token,omitempty"` // matches existing heartbeat token in DB
	SourceIp       string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatEvent) GetHeartbeatToken() string {
	if x != nil {
		return x.HeartbeatToken
	}
	return ""
}

func (x *HeartbeatEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

type ResourceSample struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerId      string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`                   // empty for host-level samples
	CpuPercent       float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`                    // host CPU% when container_id empty
	MemoryBytes      uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`                  // host mem used when container_id empty
	MemoryLimitBytes uint64                 `protobuf:"varint,4,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"` // host mem total when container_id empty
	NetworkRxBytes   uint64                 `protobuf:"varint,5,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes   uint64                 `protobuf:"varint,6,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	DiskReadBytes    uint64                 `protobuf:"varint,7,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes   uint64                 `protobuf:"varint,8,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"`
	// Host-level only (container_id empty): root filesystem capacity.
	HostDiskTotalBytes uint64 `protobuf:"varint,9,opt,name=host_disk_total_bytes,json=hostDiskTotalBytes,proto3" json:"host_disk_total_bytes,omitempty"`
	HostDiskUsedBytes  uint64 `protobuf:"varint,10,opt,name=host_disk_used_bytes,json=hostDiskUsedBytes,proto3" json:"host_disk_used_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceSample) Reset() {
	*x = ResourceSample{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSample) ProtoMessage() {}

func (x *ResourceSample) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSample.ProtoReflect.Descriptor instead.
func (*ResourceSample) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceSample) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ResourceSample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceSample) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceSample) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ResourceSample) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ResourceSample) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *ResourceSample) GetDiskReadBytes() uint64 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *ResourceSample) GetDiskWriteBytes() uint64 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

func (x *ResourceSample) GetHostDiskTotalBytes() uint64 {
	if x != nil {
		return x.HostDiskTotalBytes
	}
	return 0
}

func (x *ResourceSample) GetHostDiskUsedBytes() uint64 {
	if x != nil {
		return x.HostDiskUsedBytes
	}
	return 0
}

type CertificateInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Host              string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port              uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	SubjectCn         string                 `protobuf:"bytes,3,opt,name=subject_cn,json=subjectCn,proto3" json:"subject_cn,omitempty"`
	IssuerCn          string                 `protobuf:"bytes,4,opt,name=issuer_cn,json=issuerCn,proto3" json:"issuer_cn,omitempty"`
	NotBefore         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	FingerprintSha256 []byte                 `protobuf:"bytes,7,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	SanDns            []string               `protobuf:"bytes,8,rep,name=san_dns,json=sanDns,proto3" json:"san_dns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CertificateInfo) Reset() {
	*x = CertificateInfo{}
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateInfo) ProtoMessage() {}

func (x *CertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateInfo.ProtoReflect.Descriptor instead.
func (*CertificateInfo) Descriptor() ([]byte, []int) {
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP(), []int{14}
}

func (x *CertificateInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CertificateInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CertificateInfo) GetSubjectCn() string {
	if x != nil {
		return x.SubjectCn
	}
	return ""
}

func (x *CertificateInfo) GetIssuerCn() string {
	if x != nil {
		return x.IssuerCn
	}
	return ""
}

func (x *CertificateInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateInfo) GetFingerprintSha256() []byte {
	if x != nil {
		return x.FingerprintSha256
	}
	return nil
}

func (x *CertificateInfo) GetSanDns() []string {
	if x != nil {
		return x.SanDns
	}
	return nil
}

var File_specs_012_multiserver_pro_contracts_ingest_proto protoreflect.FileDescriptor

const file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc = "" +
	"\n" +
	"0specs/012-multiserver-pro/contracts/ingest.proto\x12\x13maintenant.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12)\n" +
	"\x10enrollment_token\x18\x03 \x01(\tR\x0fenrollmentToken\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_arch\x18\x05 \x01(\tR\x06osArch\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12G\n" +
	"\x10detected_runtime\x18\a \x01(\x0e2\x1c.maintenant.agent.v1.RuntimeR\x0fdetectedRuntime\x12\x14\n" +
	"\x05label\x18\b \x01(\tR\x05label\"\x94\x01\n" +
	"\x10RegisterResponse\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12C\n" +
	"\fagent_config\x18\x02 \x01(\v2 .maintenant.agent.v1.AgentConfigR\vagentConfig\"\xd4\x01\n" +
	"\vAgentConfig\x12G\n" +
	" resource_sample_interval_seconds\x18\x01 \x01(\rR\x1dresourceSampleIntervalSeconds\x12I\n" +
	"!certificate_scan_interval_seconds\x18\x02 \x01(\rR\x1ecertificateScanIntervalSeconds\x121\n" +
	"\x15max_events_per_second\x18\x03 \x01(\rR\x12maxEventsPerSecond\"\x8c\x01\n" +
	"\rClientMessage\x127\n" +
	"\x04auth\x18\x01 \x01(\v2!.maintenant.agent.v1.AuthResponseH\x00R\x04auth\x127\n" +
	"\x05event\x18\x02 \x01(\v2\x1f.maintenant.agent.v1.AgentEventH\x00R\x05eventB\t\n" +
	"\apayload\"\xcb\x01\n" +
	"\rServerMessage\x12B\n" +
	"\tchallenge\x18\x01 \x01(\v2\".maintenant.agent.v1.AuthChallengeH\x00R\tchallenge\x121\n" +
	"\x03ack\x18\x02 \x01(\v2\x1d.maintenant.agent.v1.EventAckH\x00R\x03ack\x128\n" +
	"\x05error\x18\x03 \x01(\v2 .maintenant.agent.v1.StreamErrorH\x00R\x05errorB\t\n" +
	"\apayload\"%\n" +
	"\rAuthChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"e\n" +
	"\fAuthResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"m\n" +
	"\bEventAck\x12$\n" +
	"\x0elast_event_seq\x18\x01 \x01(\x04R\flastEventSeq\x12;\n" +
	"\vreceived_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"a\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\"\xf2\x03\n" +
	"\n" +
	"AgentEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12C\n" +
	"\tcontainer\x18\n" +
	" \x01(\v2#.maintenant.agent.v1.ContainerEventH\x00R\tcontainer\x12@\n" +
	"\bendpoint\x18\v \x01(\v2\".maintenant.agent.v1.EndpointEventH\x00R\bendpoint\x12C\n" +
	"\theartbeat\x18\f \x01(\v2#.maintenant.agent.v1.HeartbeatEventH\x00R\theartbeat\x12A\n" +
	"\bresource\x18\r \x01(\v2#.maintenant.agent.v1.ResourceSampleH\x00R\bresource\x12H\n" +
	"\vcertificate\x18\x0e \x01(\v2$.maintenant.agent.v1.CertificateInfoH\x00R\vcertificateB\x06\n" +
	"\x04body\"\xa1\x03\n" +
	"\x0eContainerEvent\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x129\n" +
	"\x05state\x18\x05 \x01(\x0e2#.maintenant.agent.v1.ContainerStateR\x05state\x12%\n" +
	"\x0estatus_message\x18\x06 \x01(\tR\rstatusMessage\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12G\n" +
	"\x06labels\x18\b \x03(\v2/.maintenant.agent.v1.ContainerEvent.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\rEndpointEvent\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.maintenant.agent.v1.EndpointStatusR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x04R\tlatencyMs\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"V\n" +
	"\x0eHeartbeatEvent\x12'\n" +
	"\x0fheartbeat_token\x18\x01 \x01(\tR\x0eheartbeatToken\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\"\xaf\x03\n" +
	"\x0eResourceSample\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x04 \x01(\x04R\x10memoryLimitBytes\x12(\n" +
	"\x10network_rx_bytes\x18\x05 \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x06 \x01(\x04R\x0enetworkTxBytes\x12&\n" +
	"\x0fdisk_read_bytes\x18\a \x01(\x04R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\b \x01(\x04R\x0ediskWriteBytes\x121\n" +
	"\x15host_disk_total_bytes\x18\t \x01(\x04R\x12hostDiskTotalBytes\x12/\n" +
	"\x14host_disk_used_bytes\x18\n" +
	" \x01(\x04R\x11hostDiskUsedBytes\"\xb1\x02\n" +
	"\x0fCertificateInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"subject_cn\x18\x03 \x01(\tR\tsubjectCn\x12\x1b\n" +
	"\tissuer_cn\x18\x04 \x01(\tR\bissuerCn\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12-\n" +
	"\x12fingerprint_sha256\x18\a \x01(\fR\x11fingerprintSha256\x12\x17\n" +
	"\asan_dns\x18\b \x03(\tR\x06sanDns*a\n" +
	"\aRuntime\x12\x17\n" +
	"\x13RUNTIME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRUNTIME_DOCKER\x10\x01\x12\x11\n" +
	"\rRUNTIME_SWARM\x10\x02\x12\x16\n" +
	"\x12RUNTIME_KUBERNETES\x10\x03*\xfb\x01\n" +
	"\x0eContainerState\x12\x1f\n" +
	"\x1bCONTAINER_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTAINER_STATE_CREATED\x10\x01\x12\x1b\n" +
	"\x17CONTAINER_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16CONTAINER_STATE_PAUSED\x10\x03\x12\x1e\n" +
	"\x1aCONTAINER_STATE_RESTARTING\x10\x04\x12\x1c\n" +
	"\x18CONTAINER_STATE_REMOVING\x10\x05\x12\x1a\n" +
	"\x16CONTAINER_STATE_EXITED\x10\x06\x12\x18\n" +
	"\x14CONTAINER_STATE_DEAD\x10\a*\x81\x01\n" +
	"\x0eEndpointStatus\x12\x1f\n" +
	"\x1bENDPOINT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENDPOINT_STATUS_UP\x10\x01\x12\x18\n" +
	"\x14ENDPOINT_STATUS_DOWN\x10\x02\x12\x1c\n" +
	"\x18ENDPOINT_STATUS_DEGRADED\x10\x032\xba\x01\n" +
	"\x06Ingest\x12\\\n" +
	"\rRegisterAgent\x12$.maintenant.agent.v1.RegisterRequest\x1a%.maintenant.agent.v1.RegisterResponse\x12R\n" +
	"\x04Push\x12\".maintenant.agent.v1.ClientMessage\x1a\".maintenant.agent.v1.ServerMessage(\x010\x01B9Z7github.com/kolapsis/maintenant/internal/agentpb;agentpbb\x06proto3"

var (
	file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescOnce sync.Once
	file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescData []byte
)

func file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescGZIP() []byte {
	file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescOnce.Do(func() {
		file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc), len(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc)))
	})
	return file_specs_012_multiserver_pro_contracts_ingest_proto_rawDescData
}

var file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_specs_012_multiserver_pro_contracts_ingest_proto_goTypes = []any{
	(Runtime)(0),                  // 0: maintenant.agent.v1.Runtime
	(ContainerState)(0),           // 1: maintenant.agent.v1.ContainerState
	(EndpointStatus)(0),           // 2: maintenant.agent.v1.EndpointStatus
	(*RegisterRequest)(nil),       // 3: maintenant.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 4: maintenant.agent.v1.RegisterResponse
	(*AgentConfig)(nil),           // 5: maintenant.agent.v1.AgentConfig
	(*ClientMessage)(nil),         // 6: maintenant.agent.v1.ClientMessage
	(*ServerMessage)(nil),         // 7: maintenant.agent.v1.ServerMessage
	(*AuthChallenge)(nil),         // 8: maintenant.agent.v1.AuthChallenge
	(*AuthResponse)(nil),          // 9: maintenant.agent.v1.AuthResponse
	(*EventAck)(nil),              // 10: maintenant.agent.v1.EventAck
	(*StreamError)(nil),           // 11: maintenant.agent.v1.StreamError
	(*AgentEvent)(nil),            // 12: maintenant.agent.v1.AgentEvent
	(*ContainerEvent)(nil),        // 13: maintenant.agent.v1.ContainerEvent
	(*EndpointEvent)(nil),         // 14: maintenant.agent.v1.EndpointEvent
	(*HeartbeatEvent)(nil),        // 15: maintenant.agent.v1.HeartbeatEvent
	(*ResourceSample)(nil),        // 16: maintenant.agent.v1.ResourceSample
	(*CertificateInfo)(nil),       // 17: maintenant.agent.v1.CertificateInfo
	nil,                           // 18: maintenant.agent.v1.ContainerEvent.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_specs_012_multiserver_pro_contracts_ingest_proto_depIdxs = []int32{
	0,  // 0: maintenant.agent.v1.RegisterRequest.detected_runtime:type_name -> maintenant.agent.v1.Runtime
	19, // 1: maintenant.agent.v1.RegisterResponse.server_time:type_name -> google.protobuf.Timestamp
	5,  // 2: maintenant.agent.v1.RegisterResponse.agent_config:type_name -> maintenant.agent.v1.AgentConfig
	9,  // 3: maintenant.agent.v1.ClientMessage.auth:type_name -> maintenant.agent.v1.AuthResponse
	12, // 4: maintenant.agent.v1.ClientMessage.event:type_name -> maintenant.agent.v1.AgentEvent
	8,  // 5: maintenant.agent.v1.ServerMessage.challenge:type_name -> maintenant.agent.v1.AuthChallenge
	10, // 6: maintenant.agent.v1.ServerMessage.ack:type_name -> maintenant.agent.v1.EventAck
	11, // 7: maintenant.agent.v1.ServerMessage.error:type_name -> maintenant.agent.v1.StreamError
	19, // 8: maintenant.agent.v1.EventAck.received_at:type_name -> google.protobuf.Timestamp
	19, // 9: maintenant.agent.v1.AgentEvent.observed_at:type_name -> google.protobuf.Timestamp
	13, // 10: maintenant.agent.v1.AgentEvent.container:type_name -> maintenant.agent.v1.ContainerEvent
	14, // 11: maintenant.agent.v1.AgentEvent.endpoint:type_name -> maintenant.agent.v1.EndpointEvent
	15, // 12: maintenant.agent.v1.AgentEvent.heartbeat:type_name -> maintenant.agent.v1.HeartbeatEvent
	16, // 13: maintenant.agent.v1.AgentEvent.resource:type_name -> maintenant.agent.v1.ResourceSample
	17, // 14: maintenant.agent.v1.AgentEvent.certificate:type_name -> maintenant.agent.v1.CertificateInfo
	1,  // 15: maintenant.agent.v1.ContainerEvent.state:type_name -> maintenant.agent.v1.ContainerState
	19, // 16: maintenant.agent.v1.ContainerEvent.started_at:type_name -> google.protobuf.Timestamp
	18, // 17: maintenant.agent.v1.ContainerEvent.labels:type_name -> maintenant.agent.v1.ContainerEvent.LabelsEntry
	2,  // 18: maintenant.agent.v1.EndpointEvent.status:type_name -> maintenant.agent.v1.EndpointStatus
	19, // 19: maintenant.agent.v1.CertificateInfo.not_before:type_name -> google.protobuf.Timestamp
	19, // 20: maintenant.agent.v1.CertificateInfo.not_after:type_name -> google.protobuf.Timestamp
	3,  // 21: maintenant.agent.v1.Ingest.RegisterAgent:input_type -> maintenant.agent.v1.RegisterRequest
	6,  // 22: maintenant.agent.v1.Ingest.Push:input_type -> maintenant.agent.v1.ClientMessage
	4,  // 23: maintenant.agent.v1.Ingest.RegisterAgent:output_type -> maintenant.agent.v1.RegisterResponse
	7,  // 24: maintenant.agent.v1.Ingest.Push:output_type -> maintenant.agent.v1.ServerMessage
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_specs_012_multiserver_pro_contracts_ingest_proto_init() }
func file_specs_012_multiserver_pro_contracts_ingest_proto_init() {
	if File_specs_012_multiserver_pro_contracts_ingest_proto != nil {
		return
	}
	file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientMessage_Auth)(nil),
		(*ClientMessage_Event)(nil),
	}
	file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_Challenge)(nil),
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_Error)(nil),
	}
	file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes[9].OneofWrappers = []any{
		(*AgentEvent_Container)(nil),
		(*AgentEvent_Endpoint)(nil),
		(*AgentEvent_Heartbeat)(nil),
		(*AgentEvent_Resource)(nil),
		(*AgentEvent_Certificate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc), len(file_specs_012_multiserver_pro_contracts_ingest_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_specs_012_multiserver_pro_contracts_ingest_proto_goTypes,
		DependencyIndexes: file_specs_012_multiserver_pro_contracts_ingest_proto_depIdxs,
		EnumInfos:         file_specs_012_multiserver_pro_contracts_ingest_proto_enumTypes,
		MessageInfos:      file_specs_012_multiserver_pro_contracts_ingest_proto_msgTypes,
	}.Build()
	File_specs_012_multiserver_pro_contracts_ingest_proto = out.File
	file_specs_012_multiserver_pro_contracts_ingest_proto_goTypes = nil
	file_specs_012_multiserver_pro_contracts_ingest_proto_depIdxs = nil
}
